python3 diffusion/train.py \
    --mode online \
    --name online_exp \
    --group my_online_tests \
    --buffer_size 50000 \
    --online_rounds 40 \
    --iterations_per_round 1000 \
    --batch_size 256 \
    --lr 5e-6 \
    --offline_name test1 \
    --eval_datasets /home/min414/data2/extra_storage/BoB_3.pickle \
    --use_wandb